MySite_Asp_Net/Controllers/MainPageController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MySite_Asp_Net.Controllers
{
    public class MainPageController : Controller
    {
        public IActionResult ViewStart()
        {
            return View();
        }
    }
}

MySite_Asp_Net/Views/Shared/Layout.cshtml
@*@using Microsoft.AspNetCore.Authorization*@

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <!--link rel="stylesheet" href="~/css/site.css"/>-->      @*Додані ссилки з wwwroot i NuGet Package/*@
    <!--<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>-->
    <script src="https://cdn.jsdelivr.net/npm/popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</head>
<body>
    <header class="site-header sticky-top p-3 bg-dark text-white ">
        <nav class="container-fluid d-flex flex-column flex-md-row justify-content-between">
            <a class="navbar-brand py-0" href="@Url.Action("ViewStart", "MainPage")" aria-label="Product">
                <h3 class="float-md-start mb-2"><font style="vertical-align: inherit;">StorageShop</font></h3>
            </a>

            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                <li class="nav-link text-white">@Html.ActionLink("Categories", "AllCategories", "Category")</li>

                <li class="nav-link text-white">@Html.ActionLink("Products", "AllProducts", "Product")</li>
                <li class="nav-link text-white">@Html.ActionLink("Orders", "AllOrders", "Order")</li>
            </ul>
            @if (User.Identity.IsAuthenticated)
            {
                <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                    @if (User.IsInRole("admin"))
                    {
                        <li class="nav-link text-white">@Html.ActionLink("AllUsers", "AllUsers", "Admin")</li>
                    }
                    <li class="nav-link text-light"><p><i>@User.Identity.Name</i></p></li>
                    <li class="nav-link text-white"><a href="~/Profile/ProfileUser/@User.Identity.Name">Profile</a> </li>
                    <li class="nav-link text-light">
                        <button type="button" class="btn btn-warning">@Html.ActionLink("Logout", "Logout", "Account")</button>
                    </li>
                </ul>
            }
            else
            {
                <button type="button" class="btn btn-link">@Html.ActionLink("Registration", "Register", "Account")</button>
                <button type="button" class="btn btn-light">@Html.ActionLink("Login", "Login", "Account")</button>
            }
        </nav>
    </header>


    <main class="bg-warning">
        @RenderBody()   @*для відображання вмісту МАКЕТ-сторінки (Layout) *@
        @*@RenderSection()  для впорядкування і розміщення певних елементів на сторінці. *@
        <br />
        <div class="container-fluid">
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 g-2">

                <div class="col">
                    <div class="card shadow-sm bg-info text-light">
                        <img src="https://agropolit.com/media/news/original/00/07/7125/top-15-tovariv-yaki-naybilshe-podeshevshali-ta-podorozhchali-za-rik-2-10997.jpg" class="img-responsive" />
                        <div class="card-body">
                            <div class="d-flex justify-content-between align-items-center">
                                <a href="~/Product/AllProducts/">Великий вибір товарів.</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col">
                    <div class="card shadow-sm bg-info text-light">
                        <img src="http://www.mukachevo.net/Content/img/news/481/p_481206_1_slidertop2.jpg" class="img-responsive" />
                        <div class="card-body">
                            <div class="d-flex justify-content-between align-items-center">
                                <a href="~/Product/AllProducts/">Цікаві товари для подарунків.</a>                                
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <br /><br />
    </main>
    <footer class="bg-warning">
        <div class="container-fluid">&copy; All rights reserved!   @DateTime.Now.ToShortDateString()</div>
        <br />
    </footer>
</body>
</html>